# Site settings
title: Dreamstar Productions
email: TomGoodall@Dreamstarnow.com
twitter: dreamstarnow
facebook: Dreamstarnow
description: >
  Dreamstar Productions LLC, doing business as Dreamstar Dance, is a dance competition that was created to provide the highest quality experience to each and every studio, teacher, performer, and family.
baseurl: ""
url: "http://www.dreamstarnow.com" # the base hostname & protocol for your site

# Build settings
style_version: 1 # for browser caching
permalink: /news/:year/:month/:day/:title/

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
  
timezone:       US/Central
locale:         en_us
icon:           /images/dreamstar-logo.png

collections:
  #adding an underscore so the resulting folder will have 2 underscores
  _editable_pages:
    output: true
    permalink: /:path/
  bios:
    output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "_editable_pages"
    values:
      layout: page
